#!/bin/bash

ariana_status_file=/var/log/dstat/ariana_status.log
inotifywait_path=$(type -p inotifywait)
stop_message="ariana agent stopped"
running_message="ariana agent running"
if [ -z $inotifywait_path ]
then
	echo "need to inotify-tools package"
	exit 0;
fi

source /etc/ariana/config

while $inotifywait_path -e modify $ariana_status_file
do
	Last_Message=$(tail -n1 $ariana_status_file)
	Host_name=$(echo $Last_Message | awk '{print $1}')
	if [ $(echo $Last_Message | grep "$stop_message" | wc -l ) -eq 1  ] 
	then
		ariana_agent -d $Host_name.csv merge		
  	fi
	if [ $(echo $Last_Message | grep "$running_message" | wc -l) -eq 1 ]
	then
		if [ $(grep $Host_name $Data_Directory/$HostListFile | wc -l) -eq 0 ]
	        then
       			echo "Add "$Host_name" to "$HostListFile
			echo $Host_name >> $Data_Directory/$HostListFile
		fi
        fi
done
